### ISSUE TITLE
Prebuilt Image Download sites not available

### ISSUE THREAD

**Issue by epyzerknapp** [RBVI/ChimeraX#1]
The links in the README for accessing the prebuilt downloads are hitting 404 errors.  Have the links moved? If so, could you let me know what they are.  Posting to the github so that you only have to answer this question once!

**Comment by tomgoddard** [comment]
Our UCSF lab web servers that provide the ChimeraX build third-party library binaries are down.  Also our ChimeraX web site is down and our lab web page is down.  We are working on it and they should be up today, probably within a few hours.

**Comment by tomgoddard** [comment]
Servers are back online.
