### ISSUE TITLE
dead link?

### ISSUE THREAD

**Issue by dalekreitler-bnl** [RBVI/ChimeraX#28]
The link to download the project doesn't seem to be working:

https://www.rbvi.ucsf.edu/chimerax/

For me at least it throws a 404 with Firefox/Safari from both within and outside of my organization's vpn.

**Comment by dalekreitler-bnl** [comment]
I'm going to close this issue, because it looks like the link works now.

**Comment by zjp** [comment]
We had some trouble with one of the nodes on our servers. Thanks for opening the issue!
