### ISSUE TITLE
How to use chimerax 1.5  in centos7?

### ISSUE THREAD

**Issue by gaorongchao** [RBVI/ChimeraX#30]
Now chimerax does not provided .rpm for centos7, when use ChimeraX-1.5.tar.gz, I encounter some error ./ChimeraX: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by chimerax-1.5/bin/../lib/libpython3.9.so.1.0). 
Can you  provided a .rpm for centos7 or a tutorial to solve the problem.

Thank you very much!

**Comment by gaorongchao** [comment]
GLIBC update may lead the system can not be used.

**Comment by zjp** [comment]
ChimeraX has used Qt6 since 1.4, and we're bound by the minimum glibc version required by Qt6. You will have to find an unsupported workaround or upgrade your operating system.

**Comment by gaorongchao** [comment]
> ChimeraX has used Qt6 since 1.4, and we're bound by the minimum glibc version required by Qt6. You will have to find an unsupported workaround or upgrade your operating system.

Thank you, since 1.8 flatpak can be used in Centos7
