### ISSUE TITLE
Would you please add brief introduction of ChimeraX's pipeline?

### ISSUE THREAD

**Issue by yifan-gao-dev** [RBVI/ChimeraX#33]
Hey! I must say chimerax is a great work! I am curious about how chimerax read and use .mrc files to reconstruct 3D models, yet it is difficult for me to understand the whole project.
Would you please so kind to provide a brief introduction of chimerax's 3D reconstruction pipeline using .mrc files? Thanks a lot :)

**Comment by tomgoddard** [comment]
ChimeraX is primarily for visualization of atomic models and cryoEM maps and does not do reconstruction.  See the ChimeraX web site https://www.rbvi.ucsf.edu/chimerax/ where it is extensively documented.  Questions about how to use it can be sent to the ChimeraX mailing list https://mail.cgl.ucsf.edu/mailman/mailman3/lists/chimerax-users.cgl.ucsf.edu/
