### ISSUE TITLE
Lightweight debug / development environment 

### ISSUE THREAD

**Issue by RodenLuo** [RBVI/ChimeraX#36]
Hi, 

If I want to step into the functions in this script (https://rbvi.github.io/chimerax-recipes/fit_search/fit_search.html) and the functions called by this script, is there a lighter way than compiling the whole code base? Mainly stepping into Python, rarely C++.

Thanks,
Roden

**Comment by tomgoddard** [comment]
Setting up the Python debugger for ChimeraX is described in the ChimeraX programming manual

  https://www.cgl.ucsf.edu/chimerax/docs/devel/ides_debugging_profiling.html

I found this by googling chimerax debugging.  The script you are talking about has only about 3 interesting lines of code (I wrote  it), so I would be inclined to just put in a few print statements if you are wondering what is going on.

If you have questions about the ChimeraX fitting or any of the recipes examples, I wrote that code and you can ask the questions on the mailing list chimerax-users@cgl.ucsf.edu or if you think it is so technical it would not be of interest to others you can send me email directly goddard@sonic.net.

**Comment by RodenLuo** [comment]
Many thanks! I actually saw that page. But somehow I thought to get there, I had to go from the previous page, which is compiling...
