### ISSUE TITLE
GUI placed at weird position on startup 

### ISSUE THREAD

**Issue by RodenLuo** [RBVI/ChimeraX#38]
Hi,

(This is not a serious issue but annoying.) I'm on Win11 (observed the same on Win10 before) with two monitors. The display settings are shown below. Every time I start ChimeraX, if I move my mouse from the main display to the second display, then the ChimeraX GUI window is placed on the main display at a weird position (kind of cropped, screenshot below) that I cannot move it in any ways. If I start ChimeraX and put my mouse in the main display until the GUI is up, then everything is fine. 

![image](https://github.com/RBVI/ChimeraX/assets/8460424/a23d0d33-1ac8-4078-b62c-29e6a40c3961)

![image](https://github.com/RBVI/ChimeraX/assets/8460424/e50c39ee-83db-4678-9807-538bbdafd004)

**Comment by zjp** [comment]
I've opened a ticket for you on Trac, the issue tracker we use internally. We are contemplating moving to GitHub issues, but have not yet. 

Your issue can be found here: https://www.rbvi.ucsf.edu/trac/ChimeraX/ticket/14572

Thanks for reporting! We'll continue on Trac.
