### ISSUE TITLE
About the surface/mesh extraction algorithm

### ISSUE THREAD

**Issue by s1752729916** [RBVI/ChimeraX#45]
Hi,
 I recently tried visualizing volume data with ChimeraX and found that the surface/mesh obtained by ChimeraX is different from the result I obtained using the marching cube algorithm. I am curious about the specific algorithm used by Chimerax to extract surface/mesh, as well as the location of the corresponding source code, since I am unfamiliar with Chimerax's code.
Thanks!

**Comment by tomgoddard** [comment]
ChimeraX uses marching cubes for volume data surfaces and the C++ code is here

    https://github.com/RBVI/ChimeraX/blob/develop/src/bundles/map/_map/contour.cpp

**Comment by s1752729916** [comment]
thanks for your reply!
