### ISSUE TITLE
[FEATURE REQUEST] remote display on a compute cluster

### ISSUE THREAD

**Issue by alphataubio** [RBVI/ChimeraX#46]
im hitting the size limit of what datasets i can process and visualize on my little mac mini with 16gb ram. i tried opening a 10gb dcd trajectory but ChimeraX.app blew up to 24gb of memory usage. im not complaining, i accept that's a reasonable amount of resources to open a trajectory of that size. what im doing now is postprocessing 1 out of 10 (or 1 out of 100 frames) using mdanalysis in python then bringing that small sliced .dcd into chimerax on my home computer for visualization.

However, im trying to render a 2 minute movie for youtube at 60 frames/sec and 4k resolution. This is well beyond the capacity of my mac mini. I would guess im not the only user that's dealing with large datasets generated from simulations on clusters.

[https://www.cgl.ucsf.edu/chimerax/system_requirements.html](https://www.cgl.ucsf.edu/chimerax/system_requirements.html) :
> often provides unreliable or slow interactive performance when the rendering or display is not on the same computer that is running the application

not a problem when im on campus with a gigabit connection to the cluster(s).

> We also do not support running Chimera or ChimeraX on a virtual machine, as configuring graphics drivers to use GPU acceleration on a virtual machine presents technical issues. The ChimeraX development team does not have the computer systems on which to test these unsupported configurations.

**im willing to pitch in.** i have access to cluster nodes with 256gb memory and four V100 GPUs with 32gb each. what are the technical issues ? 

the main issue for me is actually requiring `sudo` access to install chimerax. ill never get root access to the cluster nodes (nor should i) i install all my stuff in ~/local.

**Comment by zjp** [comment]
We followed up at https://www.rbvi.ucsf.edu/trac/ChimeraX/ticket/16000
